# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Isy3303587_BIPLio7W9vlMhEXhUIPpe
"""

import pandas as pd
import numpy as np

"""PART-A Dataset understanding"""

# question 1 load dataset and display first 5 records
df=pd.read_csv('/content/Dataset 2.csv')
df.head()
# head function is used to diaplay first five rows

# question 2 determine number of rows and columns
print(df.shape)
# df.shape gives rows,columns
print(df.size)
# df.size gives total number of cells i.e, rows x columns

# question 3 display all column names
print(df.columns)

# question 4 identify numerical and categorical features.
print(df.dtypes)

# question 5 Check whether a dataset contains missing values.
df.isnull().values.any()
# returns true if any missing values present
df.isnull().sum()
# gives number of missing values in each column

"""PART-B Exploratory data analysis"""

# question 6 calculate average age of users
df['Age'].mean(0)

# question 7 Determine average watch hours per week
df['WatchHoursPerWeek'].mean()

# Question 8 find average monthly spending of users
df['MonthlySpend'].mean()

# Question 9 Count number of users in each subscription category
df['SubscriptionType'].value_counts()
# using sum function will concatenate all the strings
# count function will count all non null values
# values.count() will count for each unique category

# question 10 determine percentage of users who renewed their subscription
(df['SubscriptionRenewed']=='Yes').mean()*100

"""PART-C Data prepration"""

#question 11 Convert categorical features into numerical
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['FavoriteGenre']=le.fit_transform(df['FavoriteGenre'])
df['SubscriptionRenewed']=le.fit_transform(df['SubscriptionRenewed'])
df['SubscriptionType']=le.fit_transform(df['SubscriptionType'])
print(df.head())

# Question 12 define feature set(X) and target variable(Y) for subscription renewal prediction.
X=df.drop('SubscriptionRenewed',axis=1)
Y=df['SubscriptionRenewed']
print(X.head())
print(Y.head())

# question 13 split the dataset into training set and testing set
X=df.drop('SubscriptionRenewed',axis=1)
Y=df['SubscriptionRenewed']
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

"""PART-D Decision tree classification"""

# question 14 Train a decision tree model to predict whether a usser will renew their subscription
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
dt=DecisionTreeClassifier(random_state=42)
dt.fit(X_train,Y_train)
pred = dt.predict(X_test)
# question 15 Evaluate the model using accuracy.
print('Decision Tree Accuracy:', accuracy_score(Y_test,pred))
# question 16 Generate and interpret the confusion matrix.
print('\nConfusion Matrix')
print(confusion_matrix(Y_test,pred))

"""PART-E K-Nearest Neighbors(KNN)"""

# question 17 train a KNN classifier with K=5.
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train,Y_train)

knn_pred = knn.predict(X_test)

print('KNN Accuracy:', accuracy_score(Y_test,knn_pred))

# Question 18 compare accuracy of knn with desicion tree model
dt_acc = accuracy_score(Y_test,pred)

knn_acc = accuracy_score(Y_test,knn_pred)

print("Decision Tree:",dt_acc)
print("KNN:",knn_acc)

if dt_acc > knn_acc:
    print("Decision Tree performed better")
else:
    print("KNN performed better")

"""PART-F: Linear Regression"""

# Question 19 Train a linear regression moddel to predict monthly spending.
from sklearn.linear_model import LinearRegression
X_reg = df.drop(['Age','WatchHoursPerWeek','MonthlySpend'], axis=1)

Y_reg = df['MonthlySpend']

X_train_reg,X_test_reg,Y_train_reg,Y_test_reg = train_test_split(
    X_reg,Y_reg,test_size=0.2,random_state=42
)

# Question 20 Predict monthly spending for a new user and interpret the result.
lr = LinearRegression()

lr.fit(X_train_reg,Y_train_reg)
expected_features=X_train_reg.shape[1]
print(expected_features)

amount = lr.predict([[30,1,60000,20,3,15,5]])

print('Predicted Spending:', amount[0])
